name: bls12381
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/bls12381
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm install
      - name: Lint
        working-directory: ${{ env.working-directory }}
        run: npm run lint
      - name: Test
        working-directory: ${{ env.working-directory }}
        run: npm run test
      - name: Test
        working-directory: ${{ env.working-directory }}
        run: npm run build
